
import type { Lesson } from './types';

export const LESSON_PLAN: Lesson[] = [
  { week: 1, day: 1, phase: 'Level 1 - Client Intake & Filing Foundations (Individuals)', topic: 'Client interview', description: 'Structured intake to gather', references: 'Form 1040', part: 'Part 1', sequence: '1.1' },
  { week: 1, day: 2, phase: 'Level 1 - Client Intake & Filing Foundations (Individuals)', topic: 'Filing status and', description: 'Determine filing status and', references: 'Pub 501', part: 'Part 1', sequence: '1.1' },
  { week: 1, day: 3, phase: 'Level 1 - Client Intake & Filing Foundations (Individuals)', topic: 'ACA intake: total', description: 'Premium Tax Credit', references: 'Pub 974; Form', part: 'Part 1', sequence: '1.1' },
  { week: 1, day: 4, phase: 'Level 2 - Income & Property (Segment A)', topic: 'W-2 wages', description: 'Taxable wages, tips, and', references: 'Pub 525; Form', part: 'Part 1', sequence: '2.1' },
  { week: 1, day: 5, phase: 'Level 2 - Income & Property (Segment A)', topic: 'Interest and dividends', description: 'Interest (1099-INT) may be', references: 'Pub 550;', part: 'Part 1', sequence: '2.1' },
  { week: 2, day: 6, phase: 'Level 2 - Income & Property (Segment A)', topic: 'Self-employment', description: 'Report trade or business', references: 'Pub 334; Pub', part: 'Part 1', sequence: '2.1' },
  { week: 2, day: 7, phase: 'Level 2 - Income & Property (Segment A)', topic: 'Pass-through income', description: 'Schedule K-1', references: 'Pub 541; Form', part: 'Part 1', sequence: '2.1' },
  { week: 2, day: 8, phase: 'Level 2 - Income & Property (Segment A)', topic: 'Retirement income', description: 'Taxation of', references: 'Pub 575; Pub', part: 'Part 1', sequence: '2.2' },
  { week: 2, day: 9, phase: 'Level 2 - Income & Property (Segment A)', topic: 'Social Security/RRB', description: 'Taxability of Social Security', references: 'Pub 915', part: 'Part 1', sequence: '2.2' },
  { week: 2, day: 10, phase: 'Level 2 - Income & Property (Segment A)', topic: 'Other income', description: 'Topic: Other income. See', references: 'Relevant IRS', part: 'Part 1', sequence: '2.1' },
  { week: 3, day: 11, phase: 'Level 4 - Adjustments, Deductions & Credits (Individuals)', topic: 'Above-the-line', description: 'Topic: Above-the-line', references: 'Relevant IRS', part: 'Part 1', sequence: '2.4' },
  { week: 3, day: 12, phase: 'Level 4 - Adjustments, Deductions & Credits (Individuals)', topic: 'Itemized vs standard', description: 'Effect of filing', references: 'Form 1040 &', part: 'Part 1', sequence: '3.1' },
  { week: 3, day: 13, phase: 'Level 4 - Adjustments, Deductions & Credits (Individuals)', topic: 'Credits I', description: 'Effect of filing', references: 'Form 1040 &', part: 'Part 1', sequence: '3.2' },
  { week: 3, day: 14, phase: 'Level 4 - Adjustments, Deductions & Credits (Individuals)', topic: 'Credits II', description: 'Effect of filing', references: 'Form 1040 &', part: 'Part 1', sequence: '3.2' },
  { week: 3, day: 15, phase: 'Level 4 - Adjustments, Deductions & Credits (Individuals)', topic: 'Tax computation &', description: 'Topic: Tax computation &', references: 'Relevant IRS', part: 'Part 1', sequence: '4.1' },
  { week: 4, day: 16, phase: 'Level 3 - Income & Property (Segment B)', topic: 'Basis fundamentals', description: 'Basis rules for purchased,', references: 'Pub 551; Pub', part: 'Part 1', sequence: '2.3' },
  { week: 4, day: 17, phase: 'Level 3 - Income & Property (Segment B)', topic: 'Capital gains/losses', description: 'Capital gain/loss', references: 'Form 8949', part: 'Part 1', sequence: '2.3' },
  { week: 4, day: 18, phase: 'Level 3 - Income & Property (Segment B)', topic: 'Home sale (IRC §121)', description: 'Home sale exclusion under', references: 'Pub 523', part: 'Part 1', sequence: '2.3' },
  { week: 4, day: 19, phase: 'Level 3 - Income & Property (Segment B)', topic: 'Royalties and related', description: 'Report royalties (e.g.,', references: 'Pub 525;', part: 'Part 1', sequence: '2.1' },
  { week: 4, day: 20, phase: 'Level 3 - Income & Property (Segment B)', topic: 'Advising the individual', description: 'Topic: Advising the', references: 'Relevant IRS', part: 'Part 1', sequence: '5.1' },
  { week: 5, day: 21, phase: 'Level 5 - Specialized Individuals + Business Basics', topic: 'Estate tax', description: 'Estate tax overview: gross', references: 'Form 706', part: 'Part 1', sequence: '6.1' },
  { week: 5, day: 22, phase: 'Level 5 - Specialized Individuals + Business Basics', topic: 'Gift tax', description: 'Gift tax basics: annual', references: 'Form 709', part: 'Part 1', sequence: '6.2' },
  { week: 5, day: 23, phase: 'Level 5 - Specialized Individuals + Business Basics', topic: 'International', description: 'Key international', references: 'FinCEN 114', part: 'Part 1', sequence: '6.3' },
  { week: 5, day: 24, phase: 'Level 5 - Specialized Individuals + Business Basics', topic: 'Business entities', description: 'Comparison of entity types,', references: 'Pubs 334, 541,', part: 'Part 2', sequence: '1.1' },
  { week: 5, day: 25, phase: 'Level 5 - Specialized Individuals + Business Basics', topic: 'Corporations in', description: 'Comparison of entity types,', references: 'Pubs 334, 541,', part: 'Part 2', sequence: '1.3' },
  { week: 6, day: 26, phase: 'Level 6 - Entity Formation & Pass-Through Operations', topic: 'Forming a corporation', description: 'IRC §351 transfers to', references: 'Pub 542; Form', part: 'Part 2', sequence: '1.4' },
  { week: 6, day: 27, phase: 'Level 6 - Entity Formation & Pass-Through Operations', topic: 'S corporations', description: 'Comparison of entity types,', references: 'Pubs 334, 541,', part: 'Part 2', sequence: '1.5' },
  { week: 6, day: 28, phase: 'Level 6 - Entity Formation & Pass-Through Operations', topic: 'Partnerships I', description: 'Comparison of entity types,', references: 'Pubs 334, 541,', part: 'Part 2', sequence: '1.2' },
  { week: 6, day: 29, phase: 'Level 6 - Entity Formation & Pass-Through Operations', topic: 'Partnerships II', description: 'Comparison of entity types,', references: 'Pubs 334, 541,', part: 'Part 2', sequence: '1.2' },
  { week: 6, day: 30, phase: 'Level 6 - Entity Formation & Pass-Through Operations', topic: 'Business income', description: 'Gross receipts,', references: 'Form 1125-A', part: 'Part 2', sequence: '2.1' },
  { week: 7, day: 31, phase: 'Level 7 - Business Deductions, Assets & Analysis', topic: 'Business expenses', description: 'Ordinary and necessary', references: 'Pub 535; Pub', part: 'Part 2', sequence: '2.2' },
  { week: 7, day: 32, phase: 'Level 7 - Business Deductions, Assets & Analysis', topic: 'Business assets', description: 'Topic: Business assets. See', references: 'Relevant IRS', part: 'Part 2', sequence: '2.3' },
  { week: 7, day: 33, phase: 'Level 7 - Business Deductions, Assets & Analysis', topic: 'Analysis', description: 'Topic: Analysis. See', references: 'Relevant IRS', part: 'Part 2', sequence: '2.4' },
  { week: 7, day: 34, phase: 'Level 7 - Business Deductions, Assets & Analysis', topic: 'Advising the business', description: 'Topic: Advising the', references: 'Relevant IRS', part: 'Part 2', sequence: '2.5' },
  { week: 7, day: 35, phase: 'Level 7 - Business Deductions, Assets & Analysis', topic: 'Trust & estate income', description: 'Trust and estate income', references: 'Pub 559; Form', part: 'Part 2', sequence: '3.1' },
  { week: 8, day: 36, phase: 'Level 8 - Specialized Business & Representation Kickoff', topic: 'Exempt organizations', description: 'Qualification/maintenance', references: 'Pub 557; Pub', part: 'Part 2', sequence: '3.2' },
  { week: 8, day: 37, phase: 'Level 8 - Specialized Business & Representation Kickoff', topic: 'Retirement plans', description: 'Topic: Retirement plans', references: 'Relevant IRS', part: 'Part 2', sequence: '3.3' },
  { week: 8, day: 38, phase: 'Level 8 - Specialized Business & Representation Kickoff', topic: 'Farmers', description: 'Farm income (crop,', references: 'Pub 225', part: 'Part 2', sequence: '3.4' },
  { week: 8, day: 39, phase: 'Level 8 - Specialized Business & Representation Kickoff', topic: 'Rental property', description: 'Rental real estate, real', references: 'Pub 527; Pub', part: 'Part 2', sequence: '3.5' },
  { week: 8, day: 40, phase: 'Level 9 - Representation Deep Dive (Case Building to Resolution)', topic: 'Practice before the', description: 'Who may practice before', references: 'Circular 230;', part: 'Part 3', sequence: '1.1, 1.2' },
  { week: 9, day: 41, phase: 'Level 9 - Representation Deep Dive (Case Building to Resolution)', topic: 'Sanctionable acts &', description: 'Sanctionable acts and', references: 'Circular 230;', part: 'Part 3', sequence: '1.3, 1.4' },
  { week: 9, day: 42, phase: 'Level 9 - Representation Deep Dive (Case Building to Resolution)', topic: 'Power of Attorney &', description: 'Authority granted by Form', references: 'Form 2848', part: 'Part 3', sequence: '2.1' },
  { week: 9, day: 43, phase: 'Level 9 - Representation Deep Dive (Case Building to Resolution)', topic: 'Building the case', description: 'Identify issues and obtain', references: 'IRS e-Services', part: 'Part 3', sequence: '2.2' },
  { week: 9, day: 44, phase: 'Level 9 - Representation Deep Dive (Case Building to Resolution)', topic: 'Financial situation', description: 'Evaluate ability to pay and', references: 'Pub 594; Form', part: 'Part 3', sequence: '2.3' },
  { week: 9, day: 45, phase: 'Level 9 - Representation Deep Dive (Case Building to Resolution)', topic: 'Supporting docs', description: 'Substantiation, FOIA', references: 'FOIA Guidance;', part: 'Part 3', sequence: '2.4, 2.5, 2.6' },
  { week: 10, day: 46, phase: 'Level 10 - Collections, Audits, Appeals & Filing Process + Capstone Mocks', topic: 'Collections', description: 'Collections process steps;', references: 'Form 1127', part: 'Part 3', sequence: '3.1' },
  { week: 10, day: 47, phase: 'Level 10 - Collections, Audits, Appeals & Filing Process + Capstone Mocks', topic: 'Penalties/interest', description: 'Penalty and interest', references: 'Code §§ 6404,', part: 'Part 3', sequence: '3.2' },
  { week: 10, day: 48, phase: 'Level 10 - Collections, Audits, Appeals & Filing Process + Capstone Mocks', topic: 'Audits/examinations', description: 'Examination types and', references: 'Pub 556', part: 'Part 3', sequence: '3.3' },
  { week: 10, day: 49, phase: 'Level 10 - Collections, Audits, Appeals & Filing Process + Capstone Mocks', topic: 'Appeals', description: 'Appeals rights and process,', references: 'Pub 5', part: 'Part 3', sequence: '3.4' },
  { week: 10, day: 50, phase: 'Level 10 - Collections, Audits, Appeals & Filing Process + Capstone Mocks', topic: 'Filing process', description: 'Who may practice before', references: 'Circular 230;', part: 'Part 3', sequence: '4.1, 4.2, 4.3' },
];
